/*CREATE TABLE PAISES(
    ID_PAIS INTEGER DEFAULT 0 NOT NULL PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL 
);*/

/*CREATE SEQUENCE PAISES_SEQ
    START WITH 1
    INCREMENT BY 1;*/

/*CREATE TABLE ESTADOS(
    ID_ESTADO INTEGER DEFAULT 0 NOT NULL PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    FK_ID_PAIS INTEGER NOT NULL,
    FOREIGN KEY (FK_ID_PAIS)
        REFERENCES PAISES(ID_PAIS)
);*/

/*CREATE SEQUENCE ESTADOS_SEQ
    START WITH 1
    INCREMENT BY 1;*/

/*CREATE TABLE CIDADES(
    ID_CIDADE INTEGER DEFAULT 0 NOT NULL PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    FK_ID_ESTADO INTEGER NOT NULL,
    FOREIGN KEY (FK_ID_ESTADO) 
        REFERENCES ESTADOS(ID_ESTADO)
);*/

/*CREATE SEQUENCE CIDADES_SEQ
    START WITH 1
    INCREMENT BY 1;*/
    
/*CREATE TABLE BAIRROS(
    ID_BAIRRO INTEGER DEFAULT 0 NOT NULL PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    FK_ID_CIDADE INTEGER NOT NULL,
    FOREIGN KEY (FK_ID_CIDADE) 
        REFERENCES CIDADES(ID_CIDADE)
);*/

/*CREATE SEQUENCE BAIRROS_SEQ
    START WITH 1
    INCREMENT BY 1;*/

/*CREATE TABLE ENDERECOS(
    ID_ENDERECO INTEGER DEFAULT 0 NOT NULL PRIMARY KEY,
    LOGRADOURO VARCHAR2(100) NOT NULL,
    NUMERO INTEGER NOT NULL,
    COMPLEMENTO VARCHAR2(100),
    FK_ID_BAIRRO INTEGER NOT NULL,
    FOREIGN KEY (FK_ID_BAIRRO) 
        REFERENCES BAIRROS(ID_BAIRRO)
);  */

/*CREATE SEQUENCE ENDERECOS_SEQ
    START WITH 1
    INCREMENT BY 1;*/
    
/*CREATE TABLE BANCOS(
    ID_BANCO INTEGER DEFAULT 0 NOT NULL PRIMARY KEY,
    CODIGO INTEGER DEFAULT 0 NOT NULL,
    NOME VARCHAR2(100) NOT NULL
);*/

/*CREATE SEQUENCE BANCO_SEQ
    START WITH 1
    INCREMENT BY 1;*/

/*CREATE TABLE AGENCIAS(
    ID_AGENCIA INTEGER DEFAULT 0 NOT NULL PRIMARY KEY,
    FK_ID_BANCO INTEGER DEFAULT 0 NOT NULL,
    CODIGO INTEGER DEFAULT 0 NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    FK_ID_ENDERECO INTEGER DEFAULT 0 NOT NULL,
    FOREIGN KEY (FK_ID_BANCO) 
        REFERENCES BANCOS(ID_BANCO),
    FOREIGN KEY (FK_ID_ENDERECO) 
        REFERENCES ENDERECOS(ID_ENDERECO)
);*/
    
/*CREATE SEQUENCE AGENCIAS_SEQ
    START WITH 1
    INCREMENT BY 1;*/
    
/*CREATE TABLE CORRENTISTAS(
    ID_CORRENTISTA INTEGER NOT NULL PRIMARY KEY,
    RAZAO_SOCIAL CHARACTER(11) DEFAULT NULL,
    CNPJ CHARACTER(20) DEFAULT NULL,
    TIPO VARCHAR2(30) DEFAULT NULL CHECK( TIPO IN ('PJ', 'PF', 'CONJUNTA', 'INVESTIMENTO') ) 
);

CREATE SEQUENCE CORRENTISTAS_SEQ
    START WITH 1
    INCREMENT BY 1;*/

/*CREATE TABLE AGENCIAS_X_CORRENTISTAS(
    ID_AGENCIA_X_CORRENTISTA INTEGER NOT NULL PRIMARY KEY,
    FK_ID_AGENCIA INTEGER DEFAULT 0 NOT NULL,
    FK_ID_CORRENTISTA INTEGER DEFAULT 0 NOT NULL,
    FOREIGN KEY (FK_ID_AGENCIA) 
        REFERENCES AGENCIAS(ID_AGENCIA),
    FOREIGN KEY (FK_ID_CORRENTISTA) 
        REFERENCES CORRENTISTAS(ID_CORRENTISTA)
);*/

/*CREATE SEQUENCE AGENCIAS_X_CORRENTISTAS_SEQ
    START WITH 1
    INCREMENT BY 1;*/

/*CREATE TABLE CLIENTES(
    ID_CLIENTE INTEGER NOT NULL PRIMARY KEY,
    CPF VARCHAR2(11) NOT NULL,
    NOME VARCHAR2(50) NOT NULL,
    RG VARCHAR2(20) NOT NULL,
    CONJUGE VARCHAR2(50) NOT NULL,
    ESTADO_CIVIL VARCHAR2(20) CHECK( ESTADO_CIVIL IN ('SOLTEIRO', 'CASADO', 'VIUVO', 'DIVORCIADO') ) NOT NULL,
    DATA_NASCIMENTO CHAR(10) NOT NULL,
    FK_ID_TELEFONE INTEGER NOT NULL,
    FK_ID_ENDERECO INTEGER NOT NULL,
    FOREIGN KEY (FK_ID_TELEFONE) 
        REFERENCES TELEFONES(ID_TELEFONE),
    FOREIGN KEY (FK_ID_ENDERECO)
        REFERENCES ENDERECOS(ID_ENDERECO)
);  */

/*CREATE SEQUENCE CLIENTES_SEQ
    START WITH 1
    INCREMENT BY 1;*/
    
/*CREATE TABLE EMAILS(
    ID_EMAIL INTEGER NOT NULL PRIMARY KEY,
    VALOR VARCHAR2(200) DEFAULT NULL,
    FK_ID_CLIENTE INTEGER NOT NULL,
    FOREIGN KEY (FK_ID_CLIENTE) 
        REFERENCES CLIENTES(ID_CLIENTE)
); */

/*CREATE SEQUENCE EMAILS_SEQ
    START WITH 1
    INCREMENT BY 1;*/
    
/*CREATE TABLE TELEFONES(
    ID_TELEFONE INTEGER NOT NULL PRIMARY KEY,
    NUMERO VARCHAR2(20) DEFAULT NULL,
    TIPO VARCHAR2(20) DEFAULT NULL CHECK( TIPO IN ('CELULAR', 'FIXO') ) 
);    */

/*CREATE SEQUENCE TELEFONES_SEQ
    START WITH 1
    INCREMENT BY 1;*/

/*CREATE TABLE CLIENTES_X_TELEFONES(
    ID INTEGER NOT NULL PRIMARY KEY,
    FK_ID_CLIENTE INTEGER NOT NULL,
    FK_ID_TELEFONE INTEGER NOT NULL,
    FOREIGN KEY (FK_ID_CLIENTE) 
        REFERENCES CLIENTES(ID_CLIENTE),
    FOREIGN KEY (FK_ID_TELEFONE) 
        REFERENCES TELEFONES(ID_TELEFONE)
);*/
